### ISSUE TITLE
Support for the callback time argument

### ISSUE THREAD

**Issue by QbeRoot** [alexreardon/raf-stub#1]
The vanilla `window.requestAnimationFrame` function doesn’t just call the callback with no arguments, it provides a [`DOMHighResTimeStamp`](https://developer.mozilla.org/en-US/docs/Web/API/DOMHighResTimeStamp) argument representing the time for when `requestAnimationFrame` starts to fire callbacks on that frame (see [the MDN documentation about it](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame)). Currently, callbacks that use this argument cannot be tested with raf-stub.

An easy fix for this would be to store `window.performance.now()` in a variable at the beginning of the `step` function and pass that variable to every callback in the `forEach` loop. However, this would probably not be very helpful in most cases that use the timestamp, as those usually rely on time difference rather than frame count to time the animation. The “easy fix” would really only be a framerate controller.

So I think the ideal solution would be to keep track of a fake animation time globally and have `step` accept an optional argument with a default value of `1000 / 60`, representing the fake time elapsed since the last frame.

Otherwise, great job! This is a very interesting tool for debugging animations. ^^

**Comment by alexreardon** [comment]
Thanks for the input! Thanks for the suggestions also. I will get onto it.

**Comment by alexreardon** [comment]
## `replaceRaf` argument options:

### 1

 `replaceRaf(root1, root2, ...., root15, 1000 / 60)`
if the last argument is a number then use it has the duration
pros:
- backwards compatible
- opt in
- maintains nicer api for most use cases
  cons:
- usage might be a might usual

### 2

``` js
const options = {duration: 1000/ 60};
replaceRaf(root1, root2, ...., root15, options);
```

This is similar to the previous except it takes an 'options' object.
My main concern with this is that in order to get this to work then some really dirty logic will need to happen in `replaceRaf` where it would check the presence of a `options.duration` property. However, it is totally valid to pass in a root that has an unrelated `duration` property. 

### 3

`replaceRaf([roots], options)`
I think this is the cleanest but breaks the current api. It avoids magic and confusion

**Comment by alexreardon** [comment]
I am going with option 3 as I think it is the clearest. I will also add support for the `0.3.x` api with a deprecation message.
